### ISSUE TITLE
os x mount ntfs

### ISSUE THREAD

**Issue by xtxa77** [github/welcome-to-github#5]
1  sudo nano /etc/fstab

2 LABEL=NTFS_Drive none ntfs rw,auto,nobrowse

如果名字中有空格，需要使用 \040 替换，如
LABEL=Seagate\040Backup\040Plus\040Drive none ntfs rw,auto,nobrowse

3 Ctrl + X 保存

4 退出NTFS设备，重新启动

5 因为必须使用nobrowse参数，所以只能在 /Volumes 下去找，如果需要，可以使用ln -s 做超链接

**Comment by Sanjit1** [comment]
?
